### ISSUE TITLE
Fix the vulnerability issue

### ISSUE THREAD

**Issue by nish-d** [nish-d/nish-d.github.io#1]
Fix the vulnerability issue reported.

Upgrade jquery to version 3.5.0 or later.

**Comment by chetangawai** [comment]
@nish-d Can I take this up?

**Comment by nish-d** [comment]
Sure, go ahead. @chetangawai

**Comment by chetangawai** [comment]
@nish-d Can you please assign me the issue?

**Comment by chetangawai** [comment]
@nish-d Can you please describe the issue in detailed? Where can I see the vulnerability? I tried running the application but could not see it in the console.

**Comment by nish-d** [comment]
All that needs to be done is to upgrade jquery to version 3.5.0 or higher. Test and check if everything is working fine.
